version: '3.8'
services:
  api-student-07:
    build: .
    ports:
      - "3007:3000"
    environment:
      DB_URL: mongodb://mongo-student-07:27017/CRMdb-student-07
      PORT: 3000
    depends_on:
      - mongo-student-07
  mongo-student-07:
    image: mongo:latest
    ports:
      - "27024:27017"
    volumes:
      - db-data-student-07:/data/db
volumes:
  db-data-student-07:
